name: bluetooth_mini
description: bluetooth_mini

publish_to: "none"

# 版本号
version: 2.1.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 本地化
  flutter_localizations:
    sdk: flutter
  # 数据持久化
  shared_preferences: ^2.0.11
  # http
  dio: ^4.0.5-beta1
  # loading 遮盖层
  flutter_easyloading: ^3.0.3
  # 状态管理
  provider: ^6.0.1
  # 蓝牙
  flutter_blue_plus: ^1.33.6
  syncfusion_flutter_datagrid: ^26.1.39
  intl: any
  flutter_smart_dialog: any
  sqflite: ^2.0.0+4
  path: ^1.8.0
  uuid: ^3.0.6
  fl_chart: ^0.68.0
  decimal:
  path_provider: ^2.1.5
  xml: ^6.5.0
  file_picker: ^8.1.4
  permission_handler: ^11.3.0
  # PDF生成和打印
  pdf: ^3.10.7
  printing: ^5.12.0
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

# flutter 相关的配置选项
flutter:
  # 默认的 Material Design 字体图标
  uses-material-design: true

  # 静态资源
  assets:
    - assets/images/login/
    - assets/images/home/
  # 自定义字体图标（该脚手架没有用这个，用的是 Flutter 自带的默认 Icons）
  # 使用教程 https://book.flutterchina.club/chapter3/img_and_icon.html#_3-3-2-icon
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/icons/iconfont.ttf
